<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "title": "BLUDIT",
    "slogan": "Welcome to Bludit",
    "description": "Congratulations you have successfully installed your Bludit.",
    "footer": "Copyright \u00a9 2023",
    "itemsPerPage": 6,
    "language": "en",
    "locale": "en, en_US, en_AU, en_CA, en_GB, en_IE, en_NZ",
    "timezone": "Europe\/Berlin",
    "theme": "popeye",
    "adminTheme": "booty",
    "homepage": "",
    "pageNotFound": "",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "uriCategory": "\/category\/",
    "uriBlog": "",
    "url": "http:\/\/localhost:8888",
    "emailFrom": "no-reply@localhost:8888",
    "orderBy": "date",
    "currentBuild": "0",
    "twitter": "https:\/\/twitter.com\/bludit",
    "facebook": "https:\/\/www.facebook.com\/bluditcms",
    "codepen": "",
    "github": "https:\/\/github.com\/bludit",
    "instagram": "",
    "gitlab": "",
    "linkedin": "",
    "xing": "",
    "mastodon": "",
    "dribbble": "",
    "vk": "",
    "discord": "",
    "youtube": "",
    "dateFormat": "F j, Y",
    "timeFormat": "g:i a",
    "extremeFriendly": true,
    "autosaveInterval": 2,
    "titleFormatHomepage": "{{site-slogan}} | {{site-title}}",
    "titleFormatPages": "{{page-title}} | {{site-title}}",
    "titleFormatCategory": "{{category-name}} | {{site-title}}",
    "titleFormatTag": "{{tag-name}} | {{site-title}}",
    "imageRestrict": true,
    "imageRelativeToAbsolute": false,
    "thumbnailSmallWidth": 400,
    "thumbnailSmallHeight": 400,
    "thumbnailSmallQuality": 100,
    "logo": "",
    "markdownParser": true,
    "customFields": "{}",
    "darkModeAdmin": false
}